#!/usr/bin/env bash
# setup-multi-account.sh — provision per-project gh + Claude account routing.
#
# Idempotent. Creates isolated gh config dirs, ~/.ralph/accounts.toml, and the
# ~/.zshrc blocks (gh auto-routing function + claude aliases). Prints the manual
# login steps that cannot be scripted (interactive OAuth).
#
# See MULTI_ACCOUNT_SETUP.md for the why. Edit the ACCOUNTS array below, then run.
set -euo pipefail

# ── CONFIG ────────────────────────────────────────────────────────────────────
# One line per account:  label | repo-tree | gh-username | claude-config-dir
# - label:             short id; gh dir becomes ~/.config/gh-<label>
# - repo-tree:         repos under this path (~ allowed) route to this account
# - gh-username:       the `gh auth status` account name
# - claude-config-dir: ~/.claude for the default account, ~/.claude-<label> otherwise
ACCOUNTS=(
  "avelarpablo|~/Dev/personal|avelarpablo|~/.claude"
  "shopstack|~/Dev/shopstack|pabloavelar-shopstack|~/.claude-shopstack"
)
ZSHRC="${ZSHRC:-$HOME/.zshrc}"
# ──────────────────────────────────────────────────────────────────────────────

expand() { echo "${1/#\~/$HOME}"; }
say() { printf '\033[1;34m[setup]\033[0m %s\n' "$*"; }
warn() { printf '\033[1;33m[setup]\033[0m %s\n' "$*"; }

# 1. Isolated gh config dirs ---------------------------------------------------
for row in "${ACCOUNTS[@]}"; do
  IFS='|' read -r label _tree ghuser _cdir <<<"$row"
  dir="$HOME/.config/gh-$label"
  mkdir -p "$dir"
  [[ -f "$HOME/.config/gh/config.yml" ]] && cp -n "$HOME/.config/gh/config.yml" "$dir/config.yml" 2>/dev/null || true
  cat > "$dir/hosts.yml" <<EOF
github.com:
    git_protocol: https
    users:
        $ghuser:
    user: $ghuser
EOF
  chmod 600 "$dir/hosts.yml"
  if GH_CONFIG_DIR="$dir" gh api user -q .login >/dev/null 2>&1; then
    got=$(GH_CONFIG_DIR="$dir" gh api user -q .login 2>/dev/null)
    say "gh-$label → $got  (isolated dir OK)"
  else
    warn "gh-$label: not authenticated yet. Run once:  gh auth login   (as $ghuser)"
  fi
done

# 2. ~/.ralph/accounts.toml ----------------------------------------------------
mkdir -p "$HOME/.ralph"
toml="$HOME/.ralph/accounts.toml"
{
  echo "# ralph account map — generated by setup-multi-account.sh"
  echo "# Matches repo path (longest prefix wins) → isolated gh/claude config."
  echo ""
  for row in "${ACCOUNTS[@]}"; do
    IFS='|' read -r label tree _ghuser cdir <<<"$row"
    echo "[accounts.$label]"
    echo "path = \"$tree\""
    echo "gh_config_dir = \"~/.config/gh-$label\""
    echo "claude_config_dir = \"$cdir\""
    echo ""
  done
} > "$toml"
say "wrote $toml"

# 3. ~/.zshrc blocks (idempotent via delimited markers) ------------------------
touch "$ZSHRC"

# 3a. gh auto-routing function
if ! grep -q ">>> gh account auto-routing >>>" "$ZSHRC"; then
  {
    echo ""
    echo "# >>> gh account auto-routing >>>"
    echo "gh() {"
    echo "  local ghdir=\"\""
    echo "  case \"\$PWD/\" in"
    for row in "${ACCOUNTS[@]}"; do
      IFS='|' read -r label tree _g _c <<<"$row"
      etree="$(expand "$tree")"
      printf '    "%s/"*) ghdir="%s" ;;\n' "$etree" "$HOME/.config/gh-$label"
    done
    echo "  esac"
    echo "  if [[ -n \"\$ghdir\" ]]; then GH_CONFIG_DIR=\"\$ghdir\" command gh \"\$@\"; else command gh \"\$@\"; fi"
    echo "}"
    echo "# <<< gh account auto-routing <<<"
  } >> "$ZSHRC"
  say "added gh auto-routing function to $ZSHRC"
else
  warn "gh auto-routing block already in $ZSHRC — left as-is"
fi

# 3b. claude aliases
if ! grep -q ">>> claude accounts >>>" "$ZSHRC"; then
  {
    echo ""
    echo "# >>> claude accounts >>>"
    for row in "${ACCOUNTS[@]}"; do
      IFS='|' read -r label _t _g cdir <<<"$row"
      alias_name="c${label:0:2}"   # e.g. cav, csh — adjust to taste
      echo "alias $alias_name=\"CLAUDE_CONFIG_DIR=$cdir claude\""
    done
    echo "# <<< claude accounts <<<"
  } >> "$ZSHRC"
  say "added claude aliases to $ZSHRC"
else
  warn "claude accounts block already in $ZSHRC — left as-is"
fi

# 4. Manual steps --------------------------------------------------------------
echo ""
say "Done. Remaining MANUAL steps (interactive OAuth — cannot be scripted):"
for row in "${ACCOUNTS[@]}"; do
  IFS='|' read -r label _t ghuser cdir <<<"$row"
  echo "  • Claude for '$label':  CLAUDE_CONFIG_DIR=$cdir claude   → then /login as the right account"
done
echo "  • Any GitHub account not yet logged in:  gh auth login"
echo "  • Reload shell:  source $ZSHRC"
echo ""
warn "Claude tip: always log in WITH CLAUDE_CONFIG_DIR set the same way it's consumed"
warn "(use the alias), or the login lands in the legacy keychain slot and 'auth fails'."
